config/routes.rb
Labrador::Application.routes.draw do

  devise_for :users,
    :skip =>[:registrations,:sessions],
    :controllers => {
      :registrations => "users/registrations",
      :sessions => "users/sessions"
  }

  # root to: 'pages#home'
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # root to: 'home#welcome'
  delete 'logout' => 'home#logout'

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    #get 'welcome' => 'home#welcome'
    get 'bkdatabase' => 'home#welcome', as: 'welcome'
    get '401', to: 'pages#unauthorized', as: 'unauthorized'
    get 'error', to: 'pages#error', as: 'error'
  end
  #get 'welcome' => 'home#welcome'
  get 'bkdatabase' => 'home#welcome'

  scope "data" do
    Labrador::Constants::ADAPTER_KEYS.each do |adapter|
      resources adapter, controller: 'data', adapter: adapter do
        collection do
          get :collections, action: 'collections'
          get :schema, action: 'schema'
          delete :droptable, action: 'droptable'
          post :createtable, action: 'createtable'
        end
      end
    end
  end

  delete 'data/dropdb', to: 'data#dropdb'

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :database_connections
    root to: redirect("/%{locale}/database_connections/new", status: 302)
  end
  get '/:locale/*path', to: 'pages#home'
end

app/views/shared/_app.html.erb
<div class="navbar navbar-top" data-view="header">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= new_database_connection_url(subdomain: false) %>"><img src="/assets/logo.png" alt="bkdatabase"/>BK Database</a>

      <% if current_app.connected? %>
        <div class="btn-group pull-left" data-toggle="buttons-radio" data-view="context">
          <button class="btn" data-action="schema">
            <i class="icon-list-alt"></i> <%= t('database_connection.structure') %>
        </button>
        <button class="btn active" data-action="content">
          <i class="icon-align-justify"></i> <%= t('database_connection.content') %>
      </button>
    </div>
  <% end %>

  <div class="btn-group pull-right">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="icon-folder-open"></i> <%= current_app %>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% (@applications || []).each do |app| %>
      <li>
        <a href="<%= app_url(app) %>"><%= app %></a>
      </li>
    <% end %>
    <li class="divider"></li>
    <li>
      <%= lang_switcher %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to logout_path, method: 'delete' do %>
        <i class="icon-off"></i><%= t('logout') %>
      <% end %>
    </li>
  </ul>
</div>
<a class="btn pull-right" href="<%= new_database_connection_url(subdomain: false) %>">
  <i class="icon-plus-sign"></i> <%= t('connect.title') %>
          </a>
          <div class="nav-collapse">
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid" data-view="main">
      <div class="row-fluid">
        <div class="span3">
          <div data-view="sidebar" class="well sidebar-nav">
            <%= yield :sidebar %>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div><!--/span-->
      </div><!--/row-->



    </div><!--/.fluid-container-->
    <footer data-view="footer">
      <div class="span3">
        <ul data-view="controls">
          <li data-action="create-table" data-disabled="<%= current_app.nil? %>"><i class="icon-plus"></i></li>
          <li data-action="delete-table" data-disabled="<%= current_app.nil? %>"><i class="icon-minus"></i></li>
        </ul>
        <!-- <li><i class="icon-repeat"></i></li> -->
      </div>
      <div class="span9">
        <div class="pull-right">
          <ul data-view="controls">
            <li data-action="refresh" data-disabled="<%= current_app.nil? %>"><i class="icon-repeat"></i></li>
            <li data-action="prev-page" data-disabled="<%= current_app.nil? %>"><i class="icon-chevron-left"></i></li>
            <li data-action="config">
              <i class="icon-cog"></i>
            </li>
            <li data-action="next-page" data-disabled="<%= current_app.nil? %>"><i class="icon-chevron-right"></i></li>
          </ul>
        </div>
        <div class="pull-left">
          <ul data-view="controls">
            <li data-action="create-item" data-disabled="<%= current_app.nil? %>"><i class="icon-plus"></i></li>
            <li data-action="delete-item" data-disabled="<%= current_app.nil? %>"><i class="icon-minus"></i></li>
          </ul>
        </div>
        <div class="pull-left">
          <span data-name='status'></span>
        </div>
      </div>

      <!-- modals -->
      <div class="modal hide" data-view="modal">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
          <h3><%= t('modals.settings.title') %></h3>
        </div>
        <div class="modal-body">
          <form class="form-horizontal">
            <fieldset>
              <div class="control-group">
                <label class="control-label" for="input01"><%= t('modals.settings.form.limit.label') %></label>
                <div class="controls">
                  <input type="text" class="input-mini" value="500" data-name='limit'>
                </div>
              </div>
            </fieldset>
          </form>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn" data-dismiss="modal"><%= t('modals.settings.cancel') %></a>
          <a href="#" class="btn btn-primary" data-action='apply'><%= t('modals.settings.apply') %></a>
        </div>
      </div>
      <!-- /modals -->
    </footer>

app/views/shared/_help.html.erb
<ul>
  <li>Contact to me: ductm310@gmail.com</li>
</ul>