config/routes.rb
Labrador::Application.routes.draw do

  devise_for :users,
    :skip =>[:registrations,:sessions],
    :controllers => {
      :registrations => "users/registrations",
      :sessions => "users/sessions"
  }

  # root to: 'pages#home'
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # root to: 'home#welcome'
  delete 'logout' => 'home#logout'

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    #get 'welcome' => 'home#welcome'
    get 'bkdatabase' => 'home#welcome', as: 'welcome'
    get '401', to: 'pages#unauthorized', as: 'unauthorized'
    get 'error', to: 'pages#error', as: 'error'
  end
  #get 'welcome' => 'home#welcome'
  get 'bkdatabase' => 'home#welcome'

  scope "data" do
    Labrador::Constants::ADAPTER_KEYS.each do |adapter|
      resources adapter, controller: 'data', adapter: adapter do
        collection do
          get :collections, action: 'collections'
          get :schema, action: 'schema'
          delete :droptable, action: 'droptable'
          post :createtable, action: 'createtable'
        end
      end
    end
  end

  delete 'data/dropdb', to: 'data#dropdb'

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :database_connections
    root to: redirect("/%{locale}/database_connections/new", status: 302)
  end
  get '/:locale/*path', to: 'pages#home'
end

app/models/database_connection.rb
class DatabaseConnection < ActiveRecord::Base
  belongs_to :user

  validates :adapter, presence: true
  validates :name, presence: true
  validates :host, presence: true
  validates :username, presence: true
  validates :database, presence: true
  validates :password, presence: true

end

app/controllers/database_connections_controller.rb
class DatabaseConnectionsController < ApplicationController
  include ApplicationHelper
  require Rails.root.join("lib","labrador.rb")

  before_filter :find_applications, only: [:new]
  around_filter :catch_errors, only: [:create, :destroy]

  def new
  end

  def create
    if params[:database_connection][:adapter] == "mysql"
	params[:database_connection][:username] = SecureRandom.base64(9)
	params[:database_connection][:password] = SecureRandom.base64(18)
	params[:database_connection][:host] = Labrador::Application.config.mysqlcluster[:host]
	params[:database_connection][:name] = params[:database_connection][:database]
	@dbc = current_user.database_connections.new(database_connection_params.permit(:user_id, :adapter, :name, :host, :database, :username, :password, :socket))
	db = Mysql.connect(
	Labrador::Application.config.mysqlcluster[:host],
	Labrador::Application.config.mysqlcluster[:username],
	Labrador::Application.config.mysqlcluster[:password]
	)
	# check o day
	db.query("CREATE DATABASE #{database_connection_params[:name]}")
	db.query("GRANT ALL PRIVILEGES ON #{database_connection_params[:name]}.* to '#{@dbc[:username]}'@localhost IDENTIFIED BY '#{@dbc[:password]}'")
	db.query("GRANT ALL PRIVILEGES ON #{database_connection_params[:name]}.* to '#{@dbc[:username]}'@'%' IDENTIFIED BY '#{@dbc[:password]}'")
	if @dbc.save
	app = Labrador::App.new(database_connection_params)
	Labrador::Session.add database_connection_params
	@user = current_user
	# DatabaseCreatedMailer.registration_confirmation(@user, @dbc).deliver
	redirect_to app_url(app)
	else
	render 'new'
	end
	# Labrador::Session.add database_params
	# redirect_to app_url(app)
    else
	range = [*'a'..'z', *'A'..'Z']
    	params[:database_connection][:username] = Array.new(9){range.sample}.join
    	params[:database_connection][:password] = SecureRandom.base64(18)
    	params[:database_connection][:host] = Labrador::Application.config.cassandra[:host]
    	params[:database_connection][:name] = params[:database_connection][:database]
    	@dbc = current_user.database_connections.new(database_connection_params.permit(:user_id, :adapter, :name, :host, :database, :username, :password, :socket))
    	client = Cql::Client.connect(hosts: [params[:database_connection][:host]], :credentials => {:username => Labrador::Application.config.cassandra[:username], :password => Labrador::Application.config.cassandra[:password]})
    	client.execute(%Q{CREATE KEYSPACE #{database_connection_params[:name]} WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 2 }})
    	client.execute(%Q{CREATE USER #{@dbc[:username]} WITH PASSWORD '#{@dbc[:password]}'})
    	client.execute(%Q{GRANT ALL ON KEYSPACE #{database_connection_params[:name]} TO #{@dbc[:username]}})
    	client.close
    
    	if @dbc.save
      		app = Labrador::App.new(database_connection_params)
      		Labrador::Session.add database_connection_params
      		@user = current_user
      		DatabaseCreatedMailer.registration_confirmation(@user, @dbc).deliver
      		redirect_to app_url(app)
    	else
      		render 'new'
    	end
    end
  end

  def destroy
    @db = DatabaseConnection.find(params.require(:id))
    @db.destroy
    # Labrador::Databases.clear_all
    redirect_to root_url(subdomain: false)
  end


  private

  def database_connection_params
    params[:database_connection] ||= {}
    params[:database_connection].each{|key, value| session[key] = nil if value.blank? }
    params[:database_connection]
  end

  def grant_control

  end

end

app/views/database_connections/new.html.erb
<% content_for :sidebar do %>
  <ul class="nav nav-list">
    <li class="nav-header">
      <b><%= t('applications').capitalize %></b>
    </li>
  </ul>
  <ul class="nav nav-list" data-view="collections">
    <% @applications.each do |app| %>
      <li>
        <a href="<%= app_url(app) %>"><i class="icon-folder-close"></i> <%= app %></a>
      </li>
    <% end %>
  </ul>
<% end %>

<div class="page-header">
  <!--<h1><%= t('connect.title') %><small>PostgreSQL, MongoDB, MySQL, SQLite, RethinkDB</small></h1> -->
  <h1><%= t('connect.title') %><small>MySQL, Cassandra</small></h1>
</div>
<div class="row-fluid">
  <div class="span3"></div>
  <div class="span6">
    <%= form_tag database_connections_path, method: "post", class: "form-horizontal", "data-name" => "new-database-connection-form" do %>
      <div class="control-group">
        <label class="control-label" for="adapter"><%= t('connect.adapter') %></label>
        <div class="controls">
          <select name="database_connection[adapter]" id="adapter" data-name="adapter-select">
            <!--<option value="postgresql">PostgreSQL</option>-->
            <option value="mongodb">CassandraDB</option>
            <option value="mysql">MySQL</option>
            <!--<option value="sqlite">SQLite</option>-->
            <!--<option value="rethinkdb">RethinkDB</option>-->
          </select>
        </div>
      </div>
      <!--
      <div class="control-group">
        <label class="control-label" for="name"><%= t('connect.connection_name') %></label>
        <div class="controls">
          <input type="text" id="name" placeholder="<%= t('connect.connection_name_placeholder') %>" name="database_connection[name]" />
        </div>
      </div>
      <div class="control-group" data-adapter-dependent data-postgresql data-mongodb data-mysql data-rethinkdb>
        <label class="control-label" for="host"><%= t('connect.host') %></label>
        <div class="controls">
          <input type="text" id="host" placeholder="<%= t('connect.host_placeholder') %>" name="database_connection[host]" value="127.0.0.1" />
        </div>
      </div>
      <div class="control-group" data-adapter-dependent data-postgresql data-mongodb data-mysql>
        <label class="control-label" for="inputUserName"><%= t('connect.username') %></label>
        <div class="controls">
          <input type="text" id="inputUserName" placeholder="<%= t('connect.username_placeholder') %>" name="database_connection[username]" />
        </div>
      </div>
      -->
      <div class="control-group">
        <label class="control-label" for="inputPassword"><%= t('connect.database') %></label>
        <div class="controls">
          <input type="text" id="inputPassword" placeholder="<%= t('connect.database_placeholder') %>" name="database_connection[database]" />
        </div>
      </div>
      <!--
      <div class="control-group" data-adapter-dependent data-postgresql data-mongodb data-mysql>
        <label class="control-label" for="inputPassword"><%= t('connect.password') %></label>
        <div class="controls">
          <input type="password" id="inputPassword" placeholder="<%= t('connect.password_placeholder') %>" name="database_connection[password]">
        </div>
      </div>
      <div class="control-group" data-adapter-dependent data-mysql>
        <label class="control-label" for="inputPassword"><%= t('connect.socket') %></label>
        <div class="controls">
          <input type="text" id="inputSocket" placeholder="<%= t('connect.socket_placeholder') %>" name="database_connection[socket]" />
        </div>
      </div>
      -->
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn"><%= t('connect.title') %></button>
        </div>
      </div>
    <% end %>
  </div>
</div>